%YAML:1.0

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3

Viewer.width: 300
Viewer.height: 600
Viewer.z_near: 0.1
Viewer.z_far: 2000.
Viewer.ex: 0.
Viewer.ey: -100.
Viewer.ez: 0.
Viewer.lx: 0
Viewer.ly: 0
Viewer.lz: 80.
Viewer.ux: 0.
Viewer.uy: 0.
Viewer.uz: 1.
Viewer.vp_f: 200
